events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        root /var/www/html/web;  # Asegúrate de que esta es la ruta correcta de Drupal
        index index.php index.html index.htm;

        # Permitir servir archivos estáticos (CSS, JS, imágenes)
        location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4|webm|ogg|mp3|wav|flac|aac)$ {
            expires max;
            log_not_found off;
            access_log off;
        }

        location / {
            try_files $uri /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass drupal_app:9000; # Asegúrate de que coincide con el nombre del contenedor de PHP
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }
    }
}
